language: go

sudo: false
addons:
  apt:
    packages:
    - ruby
    - ruby-dev
    - build-essential
    - rpm

go:
  - "1.12.x"

script:
  - env GO111MODULE=on go mod vendor
  - env GO111MODULE=on go build
install: true
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
